### ISSUE TITLE
Dupe bugs with Frying pan

### ISSUE THREAD

**Issue by karmarcharger** [kawaiiwolf/kawaiicrops#6] opened 2015-01-13 10:49 UTC
Recipes such as mushroom stew in frying pan can be duped when using Enderio pipes/ Pneumaticraft omnidirectional hopper to pull out... i suggest disabling machine interactions to fix the issue :3

**Comment by Xltimus** [comment] 2015-01-14 03:18
I'm still rather fond of the idea of having Thaumcraft's Golems being able to handle cooking though.

**Comment by kawaiiwolf** [comment] 2015-03-03 15:37
Fixed ! Just took a little re-writing of the tile entity, fix will be in the next release.

Automation remains intact, hoppers and enderIO item conduits work as intended, going to imagine cooking golems will work just as well.

**Closed by kawaiiwolf** 2015-03-03 15:37 UTC
